/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.formats.avro.glue.schema.registry;

import org.apache.flink.annotation.Internal;
import org.apache.flink.configuration.ReadableConfig;

import org.apache.avro.Schema;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nullable;

/**
 * Resolves the Avro schema to use for GSR serialization/deserialization based on the configured
 * options.
 *
 * <p>Resolution flow:
 *
 * <ol>
 *   <li>If {@code schema.fetchFromRegistry} is true, attempt to fetch the schema from GSR
 *   <li>If fetch fails or is disabled, check for {@code avro.namespace} / {@code avro.record-name}
 *       overrides and patch the auto-generated schema
 *   <li>Otherwise, use the auto-generated schema unchanged
 * </ol>
 */
@Internal
public class AvroSchemaResolver {

    private static final Logger LOG = LoggerFactory.getLogger(AvroSchemaResolver.class);

    /**
     * Resolves the Avro schema based on the format options and the auto-generated schema.
     *
     * @param autoGeneratedSchema the Avro schema auto-generated from the Flink RowType via {@code
     *     AvroSchemaConverter.convertToSchema(RowType)}
     * @param formatOptions the Flink format options from SQL DDL
     * @param schemaFetcher optional callback to fetch schema from GSR; may be null if fetch is not
     *     supported
     * @return the resolved Avro schema
     */
    public static Schema resolveSchema(
            Schema autoGeneratedSchema,
            ReadableConfig formatOptions,
            @Nullable SchemaFetcher schemaFetcher) {

        boolean fetchFromRegistry =
                formatOptions.get(AvroGlueFormatOptions.SCHEMA_FETCH_FROM_REGISTRY);

        if (fetchFromRegistry && schemaFetcher != null) {
            String schemaName = formatOptions.get(GlueFormatOptions.SCHEMA_NAME);
            String registryName = formatOptions.get(GlueFormatOptions.REGISTRY_NAME);
            try {
                Schema fetched = schemaFetcher.fetchSchema(registryName, schemaName);
                if (fetched != null) {
                    return fetched;
                }
            } catch (Exception e) {
                LOG.warn(
                        "Failed to fetch schema '{}' from registry '{}', "
                                + "falling back to auto-generated schema.",
                        schemaName,
                        registryName,
                        e);
            }
        }

        // Apply namespace/record-name patching if configured
        String namespace =
                formatOptions.getOptional(AvroGlueFormatOptions.AVRO_NAMESPACE).orElse(null);
        String recordName =
                formatOptions.getOptional(AvroGlueFormatOptions.AVRO_RECORD_NAME).orElse(null);

        return AvroSchemaPatcher.patchSchema(autoGeneratedSchema, namespace, recordName);
    }

    /**
     * Functional interface for fetching a schema from GSR. This allows the format factory to inject
     * the actual GSR client call without coupling this resolver to the GSR SDK directly.
     */
    @FunctionalInterface
    public interface SchemaFetcher {
        /**
         * Fetches the latest schema version from GSR.
         *
         * @param registryName the registry name
         * @param schemaName the schema name
         * @return the fetched Avro Schema, or null if not found
         * @throws Exception if the fetch fails
         */
        @Nullable
        Schema fetchSchema(String registryName, String schemaName) throws Exception;
    }

    private AvroSchemaResolver() {}
}
