/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.formats.avro.glue.schema.registry;

import org.apache.flink.annotation.Internal;
import org.apache.flink.api.common.serialization.DeserializationSchema;
import org.apache.flink.api.common.serialization.SerializationSchema;
import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.configuration.ConfigOption;
import org.apache.flink.configuration.ReadableConfig;
import org.apache.flink.formats.avro.AvroRowDataDeserializationSchema;
import org.apache.flink.formats.avro.AvroRowDataSerializationSchema;
import org.apache.flink.formats.avro.AvroToRowDataConverters;
import org.apache.flink.formats.avro.RowDataToAvroConverters;
import org.apache.flink.formats.avro.typeutils.AvroSchemaConverter;
import org.apache.flink.table.connector.ChangelogMode;
import org.apache.flink.table.connector.Projection;
import org.apache.flink.table.connector.format.DecodingFormat;
import org.apache.flink.table.connector.format.EncodingFormat;
import org.apache.flink.table.connector.format.ProjectableDecodingFormat;
import org.apache.flink.table.connector.sink.DynamicTableSink;
import org.apache.flink.table.connector.source.DynamicTableSource;
import org.apache.flink.table.data.RowData;
import org.apache.flink.table.factories.DeserializationFormatFactory;
import org.apache.flink.table.factories.DynamicTableFactory;
import org.apache.flink.table.factories.FactoryUtil;
import org.apache.flink.table.factories.SerializationFormatFactory;
import org.apache.flink.table.types.DataType;
import org.apache.flink.table.types.logical.RowType;

import org.apache.avro.Schema;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Table format factory for providing configured instances of AWS Glue Schema Registry Avro to
 * RowData {@link SerializationSchema} and {@link DeserializationSchema}.
 *
 * <p>This factory supports:
 *
 * <ul>
 *   <li>SPI discovery via identifier {@code avro-glue}
 *   <li>Projection pushdown via {@link ProjectableDecodingFormat}
 *   <li>Schema namespace/record-name patching via {@link AvroSchemaPatcher}
 *   <li>Schema fetching from GSR via {@link AvroSchemaResolver}
 * </ul>
 */
@Internal
public class GlueSchemaRegistryAvroFormatFactory
        implements DeserializationFormatFactory, SerializationFormatFactory {

    public static final String IDENTIFIER = "avro-glue";

    @Override
    public DecodingFormat<DeserializationSchema<RowData>> createDecodingFormat(
            DynamicTableFactory.Context context, ReadableConfig formatOptions) {
        FactoryUtil.validateFactoryOptions(this, formatOptions);

        return new ProjectableDecodingFormat<DeserializationSchema<RowData>>() {
            @Override
            public DeserializationSchema<RowData> createRuntimeDecoder(
                    DynamicTableSource.Context context,
                    DataType producedDataType,
                    int[][] projections) {
                producedDataType = Projection.of(projections).project(producedDataType);
                final RowType rowType = (RowType) producedDataType.getLogicalType();
                final TypeInformation<RowData> rowDataTypeInfo =
                        context.createTypeInformation(producedDataType);
                final Schema autoGeneratedSchema = AvroSchemaConverter.convertToSchema(rowType);
                final Map<String, Object> configMap =
                        GlueFormatConfigBuilder.buildConfigMap(formatOptions);
                final AvroSchemaResolver.SchemaFetcher schemaFetcher =
                        createSchemaFetcherIfEnabled(formatOptions, configMap);
                final Schema resolvedSchema =
                        AvroSchemaResolver.resolveSchema(
                                autoGeneratedSchema, formatOptions, schemaFetcher);
                return new AvroRowDataDeserializationSchema(
                        GlueSchemaRegistryAvroDeserializationSchema.forGeneric(
                                resolvedSchema, configMap),
                        AvroToRowDataConverters.createRowConverter(rowType),
                        rowDataTypeInfo);
            }

            @Override
            public ChangelogMode getChangelogMode() {
                return ChangelogMode.insertOnly();
            }
        };
    }

    @Override
    public EncodingFormat<SerializationSchema<RowData>> createEncodingFormat(
            DynamicTableFactory.Context context, ReadableConfig formatOptions) {
        FactoryUtil.validateFactoryOptions(this, formatOptions);

        return new EncodingFormat<SerializationSchema<RowData>>() {
            @Override
            public SerializationSchema<RowData> createRuntimeEncoder(
                    DynamicTableSink.Context context, DataType consumedDataType) {
                final RowType rowType = (RowType) consumedDataType.getLogicalType();
                final Schema autoGeneratedSchema = AvroSchemaConverter.convertToSchema(rowType);
                final Map<String, Object> configMap =
                        GlueFormatConfigBuilder.buildConfigMap(formatOptions);
                final AvroSchemaResolver.SchemaFetcher schemaFetcher =
                        createSchemaFetcherIfEnabled(formatOptions, configMap);
                final Schema resolvedSchema =
                        AvroSchemaResolver.resolveSchema(
                                autoGeneratedSchema, formatOptions, schemaFetcher);
                final String transportName = formatOptions.get(GlueFormatOptions.SCHEMA_NAME);
                return new AvroRowDataSerializationSchema(
                        rowType,
                        GlueSchemaRegistryAvroSerializationSchema.forGeneric(
                                resolvedSchema, transportName, configMap),
                        RowDataToAvroConverters.createConverter(rowType));
            }

            @Override
            public ChangelogMode getChangelogMode() {
                return ChangelogMode.insertOnly();
            }
        };
    }

    @Override
    public String factoryIdentifier() {
        return IDENTIFIER;
    }

    @Override
    public Set<ConfigOption<?>> requiredOptions() {
        Set<ConfigOption<?>> options = new HashSet<>();
        options.add(GlueFormatOptions.AWS_REGION);
        options.add(GlueFormatOptions.REGISTRY_NAME);
        options.add(GlueFormatOptions.SCHEMA_NAME);
        return options;
    }

    @Override
    public Set<ConfigOption<?>> optionalOptions() {
        Set<ConfigOption<?>> options = new HashSet<>();
        options.add(GlueFormatOptions.AWS_ENDPOINT);
        options.add(GlueFormatOptions.CACHE_SIZE);
        options.add(GlueFormatOptions.CACHE_TTL_MS);
        options.add(GlueFormatOptions.SCHEMA_AUTO_REGISTRATION);
        options.add(GlueFormatOptions.SCHEMA_COMPATIBILITY);
        options.add(GlueFormatOptions.SCHEMA_COMPRESSION);
        options.add(AvroGlueFormatOptions.SCHEMA_TYPE);
        options.add(AvroGlueFormatOptions.AVRO_NAMESPACE);
        options.add(AvroGlueFormatOptions.AVRO_RECORD_NAME);
        options.add(AvroGlueFormatOptions.SCHEMA_FETCH_FROM_REGISTRY);
        return options;
    }

    @Override
    public Set<ConfigOption<?>> forwardOptions() {
        return Stream.of(
                        GlueFormatOptions.AWS_REGION,
                        GlueFormatOptions.AWS_ENDPOINT,
                        GlueFormatOptions.REGISTRY_NAME,
                        GlueFormatOptions.SCHEMA_NAME,
                        GlueFormatOptions.CACHE_SIZE,
                        GlueFormatOptions.CACHE_TTL_MS,
                        GlueFormatOptions.SCHEMA_AUTO_REGISTRATION,
                        GlueFormatOptions.SCHEMA_COMPATIBILITY,
                        GlueFormatOptions.SCHEMA_COMPRESSION,
                        AvroGlueFormatOptions.SCHEMA_TYPE,
                        AvroGlueFormatOptions.AVRO_NAMESPACE,
                        AvroGlueFormatOptions.AVRO_RECORD_NAME,
                        AvroGlueFormatOptions.SCHEMA_FETCH_FROM_REGISTRY)
                .collect(Collectors.toSet());
    }

    /**
     * Creates a SchemaFetcher if fetchFromRegistry is enabled.
     *
     * @param formatOptions the format options
     * @param configMap the GSR config map
     * @return a SchemaFetcher instance, or null if fetchFromRegistry is disabled
     */
    private static AvroSchemaResolver.SchemaFetcher createSchemaFetcherIfEnabled(
            ReadableConfig formatOptions, Map<String, Object> configMap) {
        boolean fetchFromRegistry =
                formatOptions.get(AvroGlueFormatOptions.SCHEMA_FETCH_FROM_REGISTRY);
        if (fetchFromRegistry) {
            return new GlueSchemaRegistrySchemaFetcher(configMap);
        }
        return null;
    }
}
